### PR TITLE
Ember 2.0 support

### PR DESCRIPTION
**Pull request by artych**
Related to #337. 
Changes: 
- views are converted to components, names preserved,
- `collectionView` and `containerView` behavior is implemented by simple `Rows` iteration in templates,
- `rowArray (ArrayController)` is removed,
- lazy rendering logic is based on `Rows (ObjectProxies)`,
- `tableBlock` and `tableContainer` become mixins,
- data fall down and actions bubble up through all nested components, that is specified in component templates, `RegisterComponentMixin` mostly is not used,
- `didInsertElement` hook mostly transformed to `didRender`,
- public api remains unchanged, except using `layoutName` instead of `templateName` on customizing component's  template,
- all examples in demo are updated.

Since there are few tests only,  this update is in "looks like it works" state :)).
I get rid of deprecation warnings (in `ember-cli 1.13.8` with `ember 1.13.7` and `ember-data 1.13.9`), so this update might be ember 2.0 ready.

**Important: I don't update part related to globals dist and I don't compile with grunt. It should be done by somebody who is familiar with such a way of using ember-table.**

### CODE REVIEW

**Comment by artych** [comment]
On ember 2.0 now

**Comment by sweco-semtne** [comment]
Thank you for this! I've noticed that the table scrolling seems a lot slower in the 2.0 version. Is that something you've noticed too?

**Comment by artych** [comment]
Yes, lazy rendering (in `lazy-table-block` component) needs to be optimized.

**Comment by gnapse** [comment]
Great PR! Any ideas of the timetable for merging this into the main repo? Or else, how could I install the addon from this branch in the mean time? I'm working on an ember 2.0 app and would like to have this working ASAP, even if experimental.

**Comment by ajgordo** [comment]
I'm having an issue when clicking the column header. I get an error in the console:
 Uncaught Error: <my-application@component:header-cell::ember610> had no action handler for: sortByColumn
Following it through I see that header-cell has an action listed in the hbs file, but there is no corresponding action in the js file, as the error suggests. 
I was going to fix it myself, but not having really looked in to this before I wanted to make sure I wasn't missing something?

**Comment by HenryVonfire** [comment]
@ajgordo `header-cell` is a view in the original ember-table, so `sortByColumn` doesn't need to be caught, because it will rise automatically to the top. Since `header-cell`is now a component, it needs to catch it and also explicitly send it up by actions or [closure actions](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_closure-actions).

**Comment by ajgordo** [comment]
Yeah, I get that, and app/templates/components/header-cell.hbs contains {{action "sortByColumn" content}}, but addon/components/header-cell.js does not contain any reference to sortByColumn so you get an error (as mentioned) and no action to grab ahold of further up the chain. Checking other conponents like header-block or header-row, they also don't mention sortByColumn so it looks to me to be overlooked, but I wanted to see if maybe I was missing something.

**Comment by fuse-mars** [comment]
This is definitely great!

**Comment by joeruello** [comment]
Has anyone got this to work with globals yet? I couldn't get it to build properly.

**Comment by Glennvd** [comment]
Does this support sending actions from a custom table cell all the way back to the controller? Pre 1.13 using views this was easily done with this.get('controller'). However now I'm stuck passing the function through table-row, which I can't (easily?) extend myself.

**Comment by knassar** [comment]
Any word on the status of this PR? 2.0 has been out for almost 2 months now. Could really use this update.

**Comment by johnnywhitney** [comment]
+1

**Comment by Glennvd** [comment]
I've been using this pull request for about a week now and it's working great so far. The only problem I've noticed is that the lazy loading is a lot slower compared to the master. I don't know if this is because of the overhead components cause (using tables with a LOT of cells) or because of the new lazy rendering logic but scrolling smoothly is not longer an option here.

**Comment by gwak** [comment]
Hi, thanks for the hard work on this, is there any scheduled date for merging this PR into master ? I'm currently wondering whether to wait for a proper 2.0 release or build a custom simple table component for an app I'm building. Thanks.

**Comment by DanChadwick** [comment]
I've been using this too. Once I converted my app to ember 2.1.0, this PR works well. It would be good to know if this is the future of the addon and when it might be optimized and committed. I'm new to ember but am happy to help in any way that I'm able.

**Comment by jmadson** [comment]
+1

**Comment by DanChadwick** [comment]
Small bug in this PR: Setting selection doesn't work. The `set()` method returns `this.get('selection')`, which makes this a no-op, since the return value is what is cached. Instead, it should simply `return val;`

I'm not sure if the right process is to make a PR for this PR or what?

**Comment by artych** [comment]
You can make PR for `ember_1.13` branch on `artych/ember-table`. Your commit will appear here automatically when merged there.

**Comment by Dynasty9** [comment]
Is this going to land soon?

**Comment by ofridagan** [comment]
+1

**Comment by andrewheartsxd** [comment]
I know @ajgordo asked about this above for 'sortColumn' and it was fixed via 222641a. I was wondering if it's possible to include custom actions on a header cell without having to edit the header-row, header-table-container, and header-block component templates?

**Comment by DanChadwick** [comment]
@andrewheartsxd - I don't have much Ember experience, but the deep component hierarchy of ember-table presents a problem for sending actions. In order to add new actions, you have to customize all the intervening components and reproduce their templates with the desired additions of the bound actions.

It seems to me that sending the action directly to the table component is better. It breaks the encapsulation of the intervening components, but seem much less brittle and awkward. You need to use` send()` rather than` sendAction()`. OTOH, maybe there's a better way, since I'm new at this.

**Comment by artych** [comment]
@andrewheartsxd @DanChadwick
There are examples of dealing with actions in nested components here. 
http://alexdiliberto.com/posts/ember-closure-actions/
It helps to simplify code, and you can avoid bubling by using components with `yield` block. (I haven't tested this yet).

**Comment by DanChadwick** [comment]
@artych -- I see two issues with deeply-nested tightly-integrated components like ember-table.:
1. Having to adjust each intervening templates in the hierarchy to bind the action(s).
2. Having to manually forward the action due to a lack of action bubbling in the component hierarchy.

I couldn't tell from the post you referenced whether 1) was addressed as it demonstrated parent/child but not more deeply-nested hierarchies. I'm also not clear how yield would be used with ember-table. This would presume rewriting all the templates to use `{{yield}}`? 

Depending upon your answer, the handling of the collapse/expand action might be tweaked in the PR. Again, apologies for lack of deep Ember knowledge.

**Comment by andrewheartsxd** [comment]
@artych & @DanChadwick -- Thanks for the replies. It seems like using closure actions still requires editing the templates of each nested component.

I've gotten around it for now by using an [event bus](http://emberigniter.com/communication-between-distant-components/), which does break the encapsulation as Dan mentioned but works fine since I don't have a lot of other arbitrarily named events firing left and right.

**Comment by andrewheartsxd** [comment]
@artych: I'm pretty sure the didRender is not triggering inside the resize-handler mixin and so none of the window resize events are being registered. It does work when I change it back to didInsertElement. The didRenders in other mixins seem to fire just fine, so I'm not sure why it doesn't for the resize-handler. Any thoughts?

**Comment by cyril-sf** [comment]
Hi Everyone,

I'm the director of product engineering at Addepar. I want to apologize in behalf of Addepar for being slow to maintain Ember Table in the past months. We care about Ember and the community, and we will work on getting this available to everyone.

**Comment by DanChadwick** [comment]
@cyril-sf -- We are grateful to Addepar for your/their contribution to the community. I'm delighted to hear that ember-table is working its way up the priority queue. No apologies!

**Comment by analysisi** [comment]
@Glennvd  my project not on ember-cli ,so i rebuild it ,i can use it in the ember 2.2 ,but i realy find some performance issues , in ember 1.12,use collectionview, when move scrollbar ,don't need to create new childitem compoent, in ember 2.0, use component render childitem component , 
on move scrollbar ,use lazyContent to get datasource, and then will create new childitem component ,maybe it will get some performance down ,just may be , 

i change code ,and test , i feel the same  compared to the master

**Comment by DanChadwick** [comment]
@cyril-sf -- With the increase in activity in the 1.13 branch, I wonder if it doesn't make sense to get this huge PR committed, even if there is further work to do on performance. This will make it easier to apply commits from the other branch and keep the two branches in sync. It will also get additional usage for the 2.0 branch.

If there is a major rewrite using other lazy scrolling technology, there's no reason that can't be another major version, no?

**Comment by ScottSmix** [comment]
I agree with Dan. I think we should stabilize something that works under Ember 2.x and then find and fix the performance issues. If a rewrite is necessary, start it under a new major version or (even better) perhaps a new project. Having the project all torn apart for so long is seriously stalling progress. I want to contribute but have no idea of what to contribute to because there is no logical roadmap. I am sure there are many others in the same holding pattern.

**Comment by cyril-sf** [comment]
Merry Christmas!

I worked on @artych's PR to use Ember Collection to lazily render the table.

https://github.com/Addepar/ember-table/tree/cyril/ember-1.13

This seems to work, I'll spend more time reviewing the code/tests.

**Comment by ScottSmix** [comment]
Thanks @cyril-sf ! Hopefully I can find some time this coming week to play with your branch and give some feedback.

**Comment by andrewheartsxd** [comment]
@cyril-sf Thanks for this! I had an issue where Ember Collection was complaining:
`Uncaught Error: Assertion Failed: A helper named 'fixed-grid-layout' could not be found`
I got around this by doing `ember install https://github.com/emberjs/ember-collection.git` in my project root. 

It seems like scrolling performance hasn't really improved between @artych's PR and this one, despite the move to Ember Collection.

**Comment by cyril-sf** [comment]
@andrewheartsxd thanks for the feedback. 

I haven't tried at all beside the demo app, so I don't know yet how much it helps. But this is for sure the approach we want to take, which should enable us to merge @artych's PR and eventually contribute to Ember Collection to fix the performance issue.

**Comment by andrewheartsxd** [comment]
@cyril-sf : For a list of 87 items, 31 rows were created.

**Comment by cyril-sf** [comment]
Thanks for the feedback.

I haven't followed closely the development of Ember Collection, so I don't know yet what the problem can be. I'll dig into it.

I'll see if @artych can squash and use my commit to prepare that PR for a code review from our side. Once it's done and we are happy with the result, we'll merge it into master and release a new version.

**Comment by andrewheartsxd** [comment]
Thanks, really do appreciate all the work everyone is putting in to get this to Ember 2.0!

**Comment by artych** [comment]
> I'll see if @artych can squash and use my commit to prepare that PR for a code review from our side. 

I'll take a look this week.

**Comment by artych** [comment]
@cyril-sf Squashed with respect to commit's authors. Unfortunately, | don't have time to evaluate performance changes.

**Comment by artych** [comment]
.. and add polyfill of requestAnimationFrame to pass tests in phantomjs.

**Comment by thijsvdanker** [comment]
The build/tests failed because of the release of jQuery 1.12
Patch is on its way (https://github.com/emberjs/ember.js/pull/12787) but in the mean time you might want to lock jQuery version to 1.11.3.

**Comment by artych** [comment]
@cyril-sf I've done technical steps to make it mergeable. Unfortunately I don't have time next 2 weeks, so this PR is yours now.

**Comment by cyril-sf** [comment]
@artych Thanks for the update.

**Comment by analysisi** [comment]
tree-table base on  ember2.0,  how to make it ? ember-table 1.12 has the demo ,but ember-table2.0 no

**Comment by albertonavarro087** [comment]
Hi, Any chance to get this update soon?

**Comment by DanChadwick** [comment]
WGT using ember-collection going forward, the maintainer of ember-smoke-and-mirrors hinted that it might be a better solution than ember-collection. I'm insufficiently well-informed to have an opinion.

https://github.com/miguelcobain/ember-paper/pull/281#issuecomment-183376350
I'm not sure if this issue is the right place for this discussion, however.

**Comment by cyril-sf** [comment]
@albertonavarro087 which update are you talking about? Do you mean merging this into master?

@DanChadwick My top priority is to get that work into master. Once it's done, it's easy to swap the base implementation for the list part.

**Comment by albertonavarro087** [comment]
@cyril-sf yes, that is what I wanted to say

**Comment by DanChadwick** [comment]
Super -- I think getting this PR into ember-table and semi-stable *before* working on adopting some other lazy-rendering would be great. Have some common platform on which to contribute would be a bit help for ember 2.x.

**Comment by ewwilson** [comment]
@cyril-sf Is there an ETA when there will be an official release that supports Ember 2.x?

**Comment by cyril-sf** [comment]
@ewwilson yes! This will happen this month.

**Comment by Glennvd** [comment]
@cyril-sf any idea on the performance compared to the ember 1.12 version? We we're using the old ember-table version until now but the 1.12 version was already starting to show signs of performance issues. The 2.0 PR's I've tried so far we're all horribly unworkable. I was planning to work out my own light weight table component but now I'm hesitating again.

**Comment by cyril-sf** [comment]
@Glennvd We haven't looked at performance yet. But as this library is core to our product, we will have to take a look at it anyway.

The performance should mostly be the same as emberjs/ember-collection. I haven't played enough with it at the moment to give you a more detailed answer.

**Comment by ewwilson** [comment]
@cyril-sf I assume this is still on track to be apart of an official release soon?

**Comment by cesar82** [comment]
Any update on the official release that supports Ember 2.x?

**Comment by gnapse** [comment]
Or alternatively, how can I include the beta ember 2 support branch in my project? Can I just put

```
  "ember-table": "artych/ember-table:ember_1.13",
```

in my `package.json`?

**Comment by tuffi111** [comment]
@gnapse 
`ember install https://github.com/artych/ember-table.git#ember_1.13`
worked for me.
or via bower.json ("dependencies"): 
`"ember-table": "git://github.com/artych/ember-table.git#ember_1.13"`

**Comment by cyril-sf** [comment]
Sorry for the delay. Ember Table doesn't contain unfortunately many tests, making any upgrades overly complicated and risky, which is a reason why it's taking us so long.

This PR contains a lot of things, making it hard to review/assert (it upgrades Ember-CLI, componentize the library, migrate to Ember 2.0, rename some variables). 

I'm going to break it down into smaller chunks easier to test. #401 is the first part of that effort. I'm opening the PR while working on it, so that you can track the progress.

**Comment by SirZach** [comment]
@cyril-sf Hi! In that branch, do you know what the `RowArray` and `Row` controllers should be replaced with?

**Comment by cyril-sf** [comment]
Update to Ember-CLI 2.4.2 is ready #402 

I'll rebase #401 against it, it will be easier to write tests.

**Comment by cyril-sf** [comment]
I'm taking a step back and will add code coverage before working on the componentization of the library as it's slow and painful to do otherwise. See #403.

**Comment by ewwilson** [comment]
@cyril-sf I know how these sort of updates can go but do you have a new ETA for an official release?

**Comment by Datamance** [comment]
Following this thread with bated breath!

**Comment by scottrblock** [comment]
Hi @cyril-sf, can we expect an update/timeline on this sometime soon?

**Comment by gwak** [comment]
Hi, has the Ember 2.0 compatibility PR been abandoned ? It seems that the development has stopped for a while now.

**Comment by gwak** [comment]
How can I help if help is needed ?

**Comment by ignotus0001** [comment]
Like so many others, I'm very interested in 2.0 support. Can we at least get a "best guess" release date?

**Comment by jrhe** [comment]
Those waiting could potentially migrate to another table impelmentation such as https://github.com/offirgolan/ember-light-table

**Comment by atomiccc** [comment]
We'd love to use this in our new project, but need 2.0 support.  What is the plan for this?  Can we do anything to contribute to make this happen?

**Comment by cyril-sf** [comment]
Sorry once again for taking that long to respond.

To be clear, here is the plan:

1. add test coverage ( https://github.com/Addepar/ember-table/pull/403 )
2. convert views into components ( https://github.com/Addepar/ember-table/pull/401 )
3. replace `ListView` to keep the performance (smoke-and-mirrors?)

We have been resource constraints again lately, I still managed to make some progress on the test suite.

If you want to help, please write to me cyril (at) addepar (dot) com.

The good news is that we are hiring to have dedicated engineers working on our open source libraries. One engineer will start early September (if you're interested in working on those problems, write to me too).

**Comment by cyril-sf** [comment]
Quick update on the support for Ember 2.0 (once again sorry for not communicating frequently)

We know that what makes Ember Table great today is the ability to have a lot of rows without a performance hit. This is possible because Ember Table relies on [Ember.ListView](https://github.com/emberjs/list-view). `Ember.ListView` is not compatible with Ember  `>= 1.13.x`.

In order to have a proper replacement for that crucial part of the library, Addepar is investing in [`vertical-collection`](https://github.com/html-next/vertical-collection). You can read more about that work on our blog ( https://build.addepar.com/engineering/rendering-10-million-items-with-vertical-collection/ ). Beta 1 was released, a second beta is on its way. Our hope is that `vertical-collection` will be compatible with HTMLBars, Glimmer and Glimmer 2, allowing for smooth upgrades on that side.

As we are nearing a functional state for `vertical-collection`, it means that we are finally going to be able to upgrade Ember Table to be Ember 1.13 compatible.
We still need to decide if we want to support Ember 2.0 in the short term by using something like `ember-legacy-views` and then make changes. We'll know more about that in the next months.

Our end goal is to rewrite the library to follow modern Ember conventions, but we understand that we'll need to go through intermediate steps.

**Pull request closed without merging**
