### PR TITLE
Add back decorators/argument

### PR DESCRIPTION
**Pull request by rwwagner90**
It seems like we need this, but not sure why.

### CODE REVIEW

**Comment by mixonic** [comment]
@rwwagner90 can you describe why you think it should be added back? Is there an error or something?

**Comment by pzuraq** [comment]
Yeah I don't think this should be necessary, if you're encountering failures it's likely coming from somewhere else now that decorators aren't being included at all in `ember-table`

**Comment by rwwagner90** [comment]
@mixonic @pzuraq when I use the `Addepar/master` branch I get failures on Ember canary with messages something like `computed decorators must be instances of a computed` or something. When I add this back and yarn link, those failures go away. I'll get the exact output for you later today.

**Comment by rwwagner90** [comment]
We don't need this. Was a yarn caching issue.

**Pull request closed without merging**
