### PR TITLE
Fix footer bug & allow custom footer

### PR DESCRIPTION
**Pull request by billy-addepar**
- Fix footer bug (https://github.com/Addepar/ember-table/issues/451)
- Allow custom footer component by defining `footerComponent` (similar to custom header)

### CODE REVIEW

**Comment by billy-addepar** [comment]
@Addepar/ice

**Comment by billy-addepar** [comment]
I put this PR back to WIP as the table does not support multiple footer rows yet

**Comment by billy-addepar** [comment]
@Addepar/ice This is ready for review again. 

I take out the SASS lint as it's better to fix them all in a separate PR.

**Comment by pzuraq** [comment]
We should start squashing commits for easier review on PRs like this.

Can you add some documentation for the new feature to the Readme?

**Comment by billy-addepar** [comment]
Commits are squashed & README is updated

**Comment by cyril-sf** [comment]
Tests are not passing. Can you check that?

**Comment by pzuraq** [comment]
It's the Travis Chrome bug

**Comment by billy-addepar** [comment]
It's a Travis chrome bug. Should not have anything to do with my last commit

**Comment by billy-addepar** [comment]
Seems like Travis fixes the bug. Tests pass now 😄

**Pull request merged**
