### PR TITLE
upgrade ember-test-selectors to get around the getWithDefault deprecation

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
See: https://github.com/Addepar/ember-table/issues/846

### CODE REVIEW

**Comment by mixonic** [comment]
@NullVoxPopuli can you rebase? I'd like to sanity check this against Addepar's internal usage but it seems reasonable.

**Comment by NullVoxPopuli** [comment]
Rebased!

**Comment by mixonic** [comment]
This was rebased onto 3.0.0-3 or something. I rebased it onto the `3.0-beta` branch which is what it targets and pushed.

**Comment by mixonic** [comment]
@NullVoxPopuli per the changelog in https://github.com/simplabs/ember-test-selectors/blob/master/CHANGELOG.md, v2 of ember-test-selectors is the last version to support Ember versions before 2.16. As this library *must* support Ember 2.8 (or Addepar won't really be able to us it), we can't bump the version of the test selector dependency past 2.x at this time.

**Comment by NullVoxPopuli** [comment]
Maybe we release another v2 version that addresses the deprecation?

**Comment by mixonic** [comment]
@NullVoxPopuli Yeah honestly `getWithDefault` is very easy to avoid. It would be fairly straightforward to write the patch upgrading ember-test-selector 2.x if the maintainers are willing to accept it.

I will say that ember-table is not going to be able to drop support for 2.x (even 2.8) for a good while. I would plan for 6 months of Ember 2.8 support and a year of Ember 2.x support as a rough, very rough, estimation. I hope that context helps you figure out next steps for your own contributions/efforts.

**Comment by NullVoxPopuli** [comment]
It does, thanks! 🎉

**Pull request closed without merging**
