### PR TITLE
fix: Ensure column cell values update when columns are reordered

### PR DESCRIPTION
**Pull request by HeroicEric**
Fixes https://github.com/Addepar/ember-table/issues/808
Fixes https://github.com/Addepar/ember-table/issues/820

The idea behind this is basically the same as https://github.com/Addepar/ember-table/pull/567.

The value of `cellValue` is computed by grabbing the `columnValue.valuePath`
and then grabbing the value of the corresponding key on `rowValue`.
Basically something like `rowValue.${columnValue.valuePath}`, which is
not possible using any of the built in computed macros.

This basically uses an observer to watch for changes to
`columnValue.valuePath`, and defines/redefines `cellValue` as a computed
alias for the property at that path on `rowValue`. This ensures the
`cellValue` is correct if `columnValue.valuePath` or the actual value at
that path on `rowValue` changes. Observers aren't recommended but this
was already using one.

Previously this was solved by creating a more generic `dynamicAlias`
computed macro in https://github.com/Addepar/ember-table/pull/567. To be
honest, I was having a little trouble wrapping my head around all that
was happening in there but I think the changes in this PR accomplish the
same idea.

I'm not totally sure what the issue was with the other implementation
but, since the `dynamicAlias` macro was only used in this one place, it
feels OK to have a more simple implementation that is hard coded
specifically for this case.

--- 

Side note: I was also able to get this working by replacing the `CellWrapper` with a tracked version of the same class, which allowed me to avoid using any observers. I'd be interested in exploring some more to see if it would be feasible to conditionally swap out some of the pieces of this addon to use `@tracked` if that's something the maintainers would be open to.

### CODE REVIEW

**Review by mixonic — APPROVED** [review]
This looks great @HeroicEric. I agree that it seems a massive simplification. If I can imagine a downside, it would be that there is a performance characteristic to the custom computed alias which is desirable.

That said I'm inclined to default toward correctness regardless unless there is a failure at the scale of "occlusion no longer works" or something.

Approving and will nudge for another maintainer to review as well.

**Review by ahmacleod — APPROVED** [review]
That's the _only_ place that entire module is used? I'm in.

**Comment by mixonic** [comment]
This is now released in `3.0.2-1`, a beta release. Please test and let us know if there are any bad behaviors!

**Comment by MichalBryxi** [comment]
Is there a reason to not bump the official release (or whatever is the name of the default version one gets from npm)? Currently it's `v3.0.1`, which does not have this patch and I guess a lot of folks (including me) are bumping into this issue. Including [ember inspector](https://github.com/Addepar/ember-table/issues/899#issuecomment-897195957).

Screenshot 2021-08-18 at 20 07 06

**Comment by mixonic** [comment]
@MichalBryxi I'll bump the minor after https://github.com/Addepar/ember-table/pull/901 lands.

**Comment by mixonic** [comment]
3.0.2 is out 🎉

**Comment by srsgores** [comment]
For those who encounter this problem, our team encountered this very problem, and one of our team members discovered a fix in the form of using the value within `{{@row}}` as opposed to `{{@cell}}`.  Note that we **did** have to create a separate component for this purpose, thus using a new `get`er, though you could also opt to simply use `@row.cell.cellValue` directly in the template if you so choose (we merely did this for clarity).

**Comment by srsgores** [comment]
We encountered this problem in the latest version (at the time of this writing, `4.0.0`)

**Pull request merged**
