### PR TITLE
bugfix: first multiselection has no _lastSelectedIndex

### PR DESCRIPTION
**Pull request by frykten**
#787 

Should I add a test?

### CODE REVIEW

**Comment by mixonic** [comment]
@frykten Yes this should certainly get a test. I'm a bit surprised the functionality isn't already covered by a test. It is because the tested functionality uses click, then shift+click? And your issue is trigged by shift+click without a preceding click?

**Comment by frykten** [comment]
@mixonic Yes, that's exactly it.

What would you advise: change the method _selectRange()_ used to select from a `normal click first => shift+click second` to `shift+click first => shift+click second` or since both should be available, let's test both?

**Comment by mixonic** [comment]
Ah yes, that is the case: https://github.com/Addepar/ember-table/blob/8519064e2b7c6d596fb42ad7708e6caf6cf9c84e/addon-test-support/pages/ember-table.js#L74-L77 the test always uses a click as the starting input, then the second click is shift+click.

I think that means we have essentially left undefined what the behavior for shift+click when there is nothing selected should be.

Some existing UX to consider:

* In the MacOS finder shift+click when nothing is selected actually selects from item #1 to the clicked item.
* In a `<select multiple>` shift+click with nothing selected simply acts like a click.
* In a browser selecting text on a webpage shift+click with nothing selected acts like a click.
* In Google Sheets shift+click with nothing selected effectively select from the first item (the top-left cell) to the cell clicked.

Are there other cases to consider? We just need to make a design decision, I will raise it with some other maintainers as well.

**Comment by mixonic** [comment]
IMO `selectRange` should stay as-is, and we should add tests for this specific case.

**Comment by frykten** [comment]
@mixonic I don't see any other cases.
Could be interesting to chat about it, right. Gotta admit, we're more into `shift+click with nothing selected simply acts like a click`, here, but the other design is a good idea also.

I fixed-up the PR to add the test.

**Comment by mixonic** [comment]
@frykten ok today I got to sync up with @bantic and @twokul and we think having a shift+click without any existing selection work as a click is fine. I think this PR already reflects that 👍 

@bantic looked at the CI quickly and it seems a point revision of prettier is causing the build to fail :-/

**Comment by mixonic** [comment]
CI on master fixed as of https://github.com/Addepar/ember-table/pull/790, @frykten can you rebase this?

**Comment by frykten** [comment]
Done @mixonic

**Comment by mixonic** [comment]
Great! Thank you @frykten I'm not sure we will make a release for a week or two because of the holiday, but keep an eye out.

**Pull request merged**
