### PR TITLE
Prevent jQuery UI from moving DOM nodes itself, otherwise Ember’s morph ...

### PR DESCRIPTION
**Pull request by ebryn**
...library will lose track of DOM

### CODE REVIEW

**Comment by azirbel** [comment]
LGTM and thanks @ebryn =) but can you modify the commit message so the first line is 50 chars or less?

**Comment by ebryn** [comment]
Sorry, I merged without the commit message change :)

**Comment by azirbel** [comment]
sad_tpope

**Comment by ebryn** [comment]
Oh dang, forgot to commit the `dist` changes :(

**Pull request merged**
