### PR TITLE
Adds onColumnSort action

### PR DESCRIPTION
**Pull request by jrhe**
Fire an action when columns are sorted.

### CODE REVIEW

**Comment by azirbel** [comment]
The function `onColumnSort` is intended to be a hook you can override to get this behavior. I agree that we should add an action that fires here, but think we should give it a different name. It's also a good opportunity to stop calling this a "sort" and start calling it a "reorder".

How about `this.sendAction('columnsReordered', columns);`?

**Comment by jrhe** [comment]
The problem with columnsReordered is that its not obvious that its expecting an action. Couldn't actually get onColumnSort to work. Whatever we choose it should be consistent with other actions in the component so we should consider what other actions might be useful.

**Comment by azirbel** [comment]
I don't have strong opinions on the naming conventions for actions. What name do you prefer? I agree we should be consistent about actions as we start to introduce them.

Other actions we'll need:
* `selectionChanged`: https://github.com/Addepar/ember-table/pull/341

When using the component, it will look like this:

```
{{ember-table
  columns=tableColumns
  content=tableContent
  columnsReordered="handleColumnReorder"
}}
```

Based on that, maybe `onColumnReorder` is a better action name?

@Dylnuge @cyril-sf @igillis

**Comment by drglitch** [comment]
@azirbel I highly vote for "onColumnsReordered" or similar (notice plural too). onColumnSorted is something that should happen when a particular single column gets sorted (i.e. data in it, like being discussed in https://github.com/Addepar/ember-table/issues/31) ... so if in future ember table core supports sorting, this would become ambiguous.

**Comment by azirbel** [comment]
Merged https://github.com/Addepar/ember-table/commit/60baf95769366f8f3a78811d38236405a0be9fef, which accomplishes the same thing.

**Pull request closed without merging**
