### PR TITLE
Add a GitHub action to check for unowned files against CODEOWNERS

### PR DESCRIPTION
**Pull request by navkast**
For information on this PR, please visit: 
https://addepar.atlassian.net/wiki/spaces/EN/blog/2022/10/13/11270389844/CODEOWNERS+Check+Automation+GitHub+Action

[_Created by Sourcegraph batch change `navcast/codeowners-action`._](https://addepar.sourcegraph.com/users/navcast/batch-changes/codeowners-action)

### CODE REVIEW

**Comment by kpfefferle** [comment]
@navkast The CODEOWNERS action is failing to load here?

**Comment by navkast** [comment]
Sourcegraph is using my API token because I'm a github admin. The questions can be answered by the author of this action: Jonny Hein from EngProd.

**Review by Jonny-Hein — APPROVED** [review]
LGTM

**Review by Jonny-Hein — APPROVED** [review]
LGTM

**Review by Jonny-Hein — APPROVED** [review]
LGTM

**Comment by kpfefferle** [comment]
@Jonny-Hein @navkast I'm confused why this was force-merged when it was completely failing to load???

**Pull request merged**
