### PR TITLE
add onColumnReordered and onColumnResized actions

### PR DESCRIPTION
**Pull request by drglitch**
- related to #312 and supersedes #342
- onColumnReordered fires with three args: all columns (new), column
that was reordered, and index at which new column was placed
- onColumnResized fires with 2 args: column that was resized and new
width of the column. Note that resizing of a column can cause another
to resize if fit columns mode is on.

- manual tests passed. no automated tests ran.

### CODE REVIEW

**Comment by taras** [comment]
@drglitch if you don't mind, could you please describe the use case where you need these actions?

**Comment by drglitch** [comment]
@taras please see https://github.com/Addepar/ember-table/issues/312#issuecomment-119353690. i can go into more detail if necessary :)

**Comment by taras** [comment]
@drglitch Got it. Thanks :)

**Comment by azirbel** [comment]
Merged as https://github.com/Addepar/ember-table/commit/60baf95769366f8f3a78811d38236405a0be9fef. Thanks @drglitch!

**Pull request closed without merging**
