### PR TITLE
[CHORE] Update ember-decorators

### PR DESCRIPTION
**Pull request by cyril-sf**

### CODE REVIEW

**Comment by cyril-sf** [comment]
So this fails with Ember 1.12 because of ember-decorators/ember-decorators#148

Screen Shot 2019-03-26 at 5 25 37 PM

When `uniqBy` was added, some code was present to make sure it would not break with older versions of Ember. This protection was removed with ember-decorators/ember-decorators#308.

We can't use `ember-decorators` >= 3.1.0 without patching it.

**Comment by mixonic** [comment]
@cyril-sf what is the motivation for upgrading to `ember-decorators >= 3.1.0`, for context?

**Comment by cyril-sf** [comment]
At the very least, to keep our dependencies up to date.

**Comment by ezpuzz** [comment]
updating ember-decorators to the latest would unblock me from upgrading ember-cli-typescript in my app because having multiple versions in the dependency tree currently creates a runtime conflict and manually resolving to the newer or older is incompatible.   newer ember-cli-typescript is much faster on my project.

**Comment by cyril-sf** [comment]
As we dropped support for `ember-decorators`, I'm closing this PR.

**Pull request closed without merging**
