### PR TITLE
Upgrade several project dependencies

### PR DESCRIPTION
**Pull request by josemarluedke**
cc/ @twokul

### CODE REVIEW

**Comment by josemarluedke** [comment]
Tests are failing in `release` and `beta` channels. I believe these tests are actually broken because of changes in Ember v3.8 and above. I can confirm that `ember-table` does not work properly when used in an app with Ember v3.8.

**Comment by cyk** [comment]
I think this upgrade work is running into the same blockers as the broken build fixing efforts. In short:

1. [Master](https://travis-ci.org/Addepar/ember-table/jobs/478606931#L516) then subsequent builds began to fail as a result of a sub-dependency (`ip-regex@3.0.0`) specifying incompatible Node engine requirements (#656)
2. No problem, the latest (within constraints) of ember-cli-addon-docs patched it (#657), Travis yarn cache is cleared to pull it in
3. This uncovered a conflict with ember-cli-addon-docs ember-data dependency which manifests as [`Global error: Uncaught TypeError: Cannot read property 'prototype' of undefined`](https://travis-ci.org/Addepar/ember-table/jobs/491781352#L587) (also [last failure for this PR](https://travis-ci.org/Addepar/ember-table/jobs/496274530#L601))
4. No worries, ember-cli-addon-docs v0.6.0 patches it, so a [commit was added to #657](https://github.com/Addepar/ember-table/pull/657#issuecomment-463803992) that bumps the version. 

Finally, the [latest failure on #657](https://github.com/Addepar/ember-table/pull/657#issuecomment-465126681) is the same this branch experiences when upgrading ember-cli-addon-docs (sass import failures of tailwind styles). Thanks for reporting it in https://github.com/ember-learn/ember-cli-addon-docs/issues/326.

FWIW: I suspect that [v0.6.0](https://github.com/ember-learn/ember-cli-addon-docs/releases/tag/v0.6.0) introduced some breaking change in addition to the fix, as pinning directly to https://github.com/ember-learn/ember-cli-addon-docs/commit/97dcf3bc8478e45c217a38d15e2117df2e18c32e seems unaffected.

**Comment by josemarluedke** [comment]
@cyk What is the path forward on this then? This PR as it is, is passing (with disabled ember beta + release). 

This is just one step closer to get other dependencies up to date. We are currently blocked by `ember-table` because of its old dependency of ember-decorators, which is my primary driving motivation for this PR.

I hope we can get some progress on updating `ember-table` to latest dependencies, mainly `ember-decorators`. 🤞

**Comment by cyk** [comment]
@josemarluedke, I'd like to clarify that my previous comment means to corral related efforts and increase visibility. I think your work here is very helpful. I'm looking forward to the ember-decorator upgrades, so thank you. 🙂 

As far as the path forward, it's really a maintainers call. The two issues here are **1)** builds failing from a sub-dependency's breaking change (#656) and more recently, **2)** builds failing from incompatibilities with latest Ember (#659). 

**My 2¢** — It might be helpful to tackle the first issue with a minimal set of changes before diving into the second. We understand the breakages for the former; the latter requires more investigation and is possibly more involved. 

This makes the cause of what broke it in the first place clear and gives us a reliable base to either proceed with remaining dependency upgrades and/or fix Ember incompatibilities. Also, unblocks other PRs that might not need >= 3.8 compatibility.

If it's acceptable to allow failures for incompatible versions of Ember, then we might consider #657 fix. (We'd have to update it with reverting the last commit and adding allowed CI failures.) Of course, the yarn cache clearing is still an option as well.

**Comment by cyril-sf** [comment]
@josemarluedke Thanks for the help.

Can you rebase against master to resolve the conflict?

**Comment by josemarluedke** [comment]
@cyril-sf Just pushed a rebase. Let's see if tests pass.

**Comment by cyril-sf** [comment]
Thanks for the help!

**Pull request merged**
