### PR TITLE
Check for undefined attributeBindings

### PR DESCRIPTION
**Pull request by kpfefferle**
When we deploy our application using v3.0.2-3, we see the following console error:

```
TypeError: Cannot read property 'includes' of undefined
```

The stack trace points to https://github.com/Addepar/ember-table/blob/06ad94fc42cf68a87256faff494cf19dd84938c4/addon/components/ember-tbody/component.js#L273 which was introduced in https://github.com/Addepar/ember-table/pull/893

This PR adds an additional condition to check that `this.attributeBindings` is defined before calling `.includes()` on it. This fixes the error we see in our deployed application.

### CODE REVIEW

**Comment by mixonic** [comment]
@kpfefferle is this for Ember 4.0? Can you ensure we have coverage of a reproduction?

**Comment by kpfefferle** [comment]
@mixonic This happened in an app running Ember 3.27. This is the sort of thing that would likely be caught in a typed codebase as TS would notice that you are calling `.includes` on a property that could be `undefined`.

Do you have a suggestion how to test this case besides running our test suite against a production build (which then would drop the `data-test-*` selectors that many of our tests rely on?).

**Comment by mixonic** [comment]
@kpfefferle we can use a production build of Ember but force the `data-test-` selectors to be enabled. We're actually doing something similar for internal Addepar codebases.

Let me take a stab at adding it to the build on this PR. I'd really like to make sure this has coverage.

**Comment by shaun-addepar** [comment]
Hi, is there any update on this? We have a couple of blocker bugs([IX-322](https://addepar.atlassian.net/browse/IX-322) & [IX-323](https://addepar.atlassian.net/browse/IX-323)) in beta and staging that prevents all tables from rendering data and looks like it could be fixed by this PR.

**Comment by mixonic** [comment]
I was unable to write a test for this as ember-test-selectors itself causes `attributeBindings` to be present even if using a production builds for test.

I added a comment explaining the patch and how it relates to tests, and I also did add a production build to the test suite here because why not.

**Comment by mixonic** [comment]
Included in 3.0.2 🎉

**Pull request merged**
