### PR TITLE
Ember 1.10 / HTMLBars support

### PR DESCRIPTION
**Pull request by ebryn**

### CODE REVIEW

**Comment by azirbel** [comment]
LGTM. Will wait to merge until we release a "last 1.9" version.

**Comment by SirZach** [comment]
I'm so pumped for this PR! ember-table is great but it's the only thing holding us back from HTMLBars. Woot!

**Comment by intuitivepixel** [comment]
Go Go Ember Table :)

**Comment by azirbel** [comment]
I've made a new branch with 1.10 support. Branch here: https://github.com/Addepar/ember-table/pull/287, discussion here: https://github.com/Addepar/ember-table/issues/288.

**Pull request closed without merging**
