### PR TITLE
Ember 2.4+ does not need the assign polyfill

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by twokul** [comment]
Related to https://github.com/Addepar/ember-table/issues/819.

**Comment by twokul** [comment]
I am not sure we want to merge this into `3.0-beta` yet since we would like to drop all the "< Ember 2.4" targets but keep Ember 2.4, for now. I believe, `assign` appears in Ember proper in 2.5.

**Comment by mixonic** [comment]
I believe the correct fix here is to use native `Object.assign` and stop using Ember's API at all. Then we can drop the polyfill. The browser support commitment for ember-table is fuzzy, but we're certainly *not* supporting IE11 in 3.0 and that was really the blocker on using `Object.assign`.

https://caniuse.com/mdn-javascript_builtins_object_assign

**Comment by mixonic** [comment]
The only use of `assign` in Ember Table *is* `Object.assign`. So, I'm really not even sure what this dependency is doing. Certainly on our supported browsers it is doing nothing. Merging this.

**Pull request merged**
