### PR TITLE
Make sure the element is sortable/resizable before destroying them.

### PR DESCRIPTION
**Pull request by liuyang-li**
@cyril-sf @yayalice

### CODE REVIEW

**Comment by azirbel** [comment]
This makes sense to me, but I don't know how to judge if it is the best way. It seems especially strange to go to the controller to see if an element is sortable, rather than checking the element itself (e.g. is `.sortable` defined?).

It would be great if @ebryn or @cyril-sf could look at it.

**Comment by cyril-sf** [comment]
calling `destroy` is the way to go. It's not clear to me if there is a better way to detect if the widget has been applied to an element than to check for a css class.

This seems brittle. But at least it works.

By looking at the source code of `jquery.ui.sortable.js`, it seems like there is a `ready` flag. Something to check maybe.

**Comment by azirbel** [comment]
Sounds like Cyril is ok with it too, so LGTM.

**Comment by liuyang-li** [comment]
Thanks for the comments. I pushed the change as it is for now to unblock me for another change. Agreed that we should be looking into a long term solution to this.

**Comment by cyril-sf** [comment]
It definitely looks sad, but I haven't seen a better way to get the information.

**Pull request merged**
