### PR TITLE
Upgraded to EmberCLI 0.2.7

### PR DESCRIPTION
**Pull request by azirbel**
Same as https://github.com/Addepar/ember-table/pull/347, but:

* Rebased on master
* Use Ember version `>=1.12 <1.13` instead of `1.12.0`
* No need to change the template for configurable table; the parser was choking on a `>` sign which I fixed in a previous commit on master.

@Addepar/ui2-developers @taras

### CODE REVIEW

**Comment by azirbel** [comment]
Still need to check against JS bin and make sure that the globals build works.

**Comment by taras** [comment]
LGTM :+1:

**Comment by azirbel** [comment]
Globals build works, merge time

**Comment by taras** [comment]
WOOP WOOP

**Pull request merged**
