### PR TITLE
bugfix: allow zero for fillColumnIndex

### PR DESCRIPTION
**Pull request by MichalBryxi**
fix: #767

### CODE REVIEW

**Comment by MichalBryxi** [comment]
Ah, sorry. Was just a quick fork & fix for me in the morning. Will lint-fix next week. On my way away from computer now 😄   ⛰ 🚶

**Comment by MichalBryxi** [comment]
:high-eyebrow-emoji:
I fixed the linter error, but the floating dependencies complain about:

```
Closing tag `p` (on line 49) without an open tag.
  - errorType: Template Compiler Error
  - location:
    - column: 27
    - file: dummy/pods/docs/guides/body/occlusion/template.hbs
    - line: 36
    - treeDir: /home/travis/build/Addepar/ember-table/tmp/broccoli_persistent_filtertemplate_compiler-input_base_path-HkN3ym8g.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin. 💥
```

Not sure whether that is my fault at all?

**Comment by mixonic** [comment]
@MichalBryxi thanks for the follow through. I kicked the build and if it fails again I'll try to get a fix into another PR quickly. It seems like we should maybe pin a dependency more precisely (or there has been a regression etc upstream).

**Comment by mixonic** [comment]
Done, thanks @MichalBryxi 🎉

**Comment by mixonic** [comment]
In 2.1.13

**Pull request merged**
