### PR TITLE
overflow scroll is auto

### PR DESCRIPTION
**Pull request by addepar-andy**
reviewers: @Addepar/ice

### CODE REVIEW

**Comment by pzuraq** [comment]
`overflow: scroll` is currently how we get fixed columns, headers, and footers. Turning this off will likely break things, as the sticky elements will instead default to whatever the parent scroll container is.  Why are you trying to change it?

**Comment by addepar-andy** [comment]
because this creates scroll bars when the table when the table doesn't need them.  a table that doesn't need to scroll side to side (because you can already see all the columns) will still have the scrollbar, and you'll get ~10px of superfluous scrolling.

**Comment by pzuraq** [comment]
That sounds like a bug with antiscroll and the way it inserts scrollbars in our app, native scroll bars shouldn't be visible if the content doesn't overflow as you're describing. 

I think it would be better to manually override the overflow style in your table for the time being and keep these styles here, otherwise the default behavior will be broken for users unless they know to make `.ember-table` a scroll container.

**Comment by pzuraq** [comment]
I think this _should_ be fixed on master, if not let me know and we'll make fixing a priority.

**Pull request merged**
