### PR TITLE
Deprecate Property Fallback Lookup (no implicit this, take two)

### PR DESCRIPTION
**Pull request by johanrd**

### CODE REVIEW

**Comment by mixonic** [comment]
I've rebased and force pushed this branch.

**Comment by mixonic** [comment]
@johanrd This looks pretty great! The docs build is failing on what seems like a legit error (`.textContent` is being read off something which is now `null`) but the addon tests themselves are green 💪

**Comment by johanrd** [comment]
@mixonic thanks, the `.textContent of null` error should now be resolved

**Review by kpfefferle — APPROVED** [review]
This was suggested in #897 as a candidate for 4.0, but it's a backwards-compatible change - so I'll go ahead and merge this to `master` and then rebase the `4.0-beta` branch to pick up on these changes since they do help unblock support for Ember 4.0.

**Pull request merged**
