### PR TITLE
3.0 beta

### PR DESCRIPTION
**Pull request by twokul**
Test PR to make sure tests are good.

See: https://github.com/Addepar/ember-table/issues/819

### CODE REVIEW

**Comment by twokul** [comment]
```sh
not ok 46 Chrome 62.0 - [60047 ms] - Acceptance | docs: subcolumns docs renders cell content
    ---
        actual: >
            [object Object]
        stack: >
            Error: fetch is not defined - maybe your browser targets are not covering everything you need?
                at Module.callback (http://localhost:7357/assets/vendor.js:112532:13)
                at Module.exports (http://localhost:7357/assets/vendor.js:7315:32)
                at Module._reify (http://localhost:7357/assets/vendor.js:7352:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:7339:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:7313:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:7352:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:7339:27)
                at Module.exports (http://localhost:7357/assets/vendor.js:7313:10)
                at Module._reify (http://localhost:7357/assets/vendor.js:7352:59)
                at Module.reify (http://localhost:7357/assets/vendor.js:7339:27)
        message: >
            fetch is not defined - maybe your browser targets are not covering everything you need?
        negative: >
            false
        browser log: |
```

**Comment by juanazam** [comment]
@twokul Hey, since you guys are close to releasing, I'm seeing warnings coming from the page objects for tests:

This is the warnings: 'ember-cli-page-object.string-properties-on-definition', would you mind taking a look?

**Comment by mixonic** [comment]
> @twokul Hey, since you guys are close to releasing, I'm seeing warnings coming from the page objects for tests:
> 
> This is the warnings: 'ember-cli-page-object.string-properties-on-definition', would you mind taking a look?

@juanazam I don't want to block 3.0 on warning/deprecations from dependencies. I agree it would be ideal to ship a version of ember-table with all the page object deps upgraded, in practice it has been non-trivial to accomplish and needs attention. Related are probably:

* An attempt to bump even just `yarn.lock` https://github.com/Addepar/ember-table/pull/856
* ...then just ember-cli-addon-docs: https://github.com/Addepar/ember-table/pull/858
* ...and just ember-test-selectors: https://github.com/Addepar/ember-table/pull/847

If this warning is having a direct impact on your dev experience, we could use help figuring out these upgrade paths. I think for Addepar maintainers it is on a side burner, but not off the stove.

**Comment by juanazam** [comment]
@mixonic I don't think bumping the version is necessary, not using plain string properties on page objects should be enough (basically implementing a getter that returns the same string value that was used before).

I totally agree on **not blocking 3.0**, I'm just seeing a lot of movement here so might as well to see what you guys think.

**Comment by mixonic** [comment]
@juanazam please see https://github.com/Addepar/ember-table/pull/869 which is tracking a bump to ember-classy-page-object and ember-cli-page-object. I haven't yet been able to integrate that into our own consuming applications, there are just a lot of moving parts in the test suite. I'm not sure if we will get it landed in time for 3.0 but the path is fairly clear. I just need to get our internal apps validated with the upgrade.

**Comment by juanazam** [comment]
@mixonic thanks so much for all your work! 👏

**Comment by twokul** [comment]
The `ember-canary` scenario is failing because of [the regression](https://github.com/emberjs/ember.js/pull/19390/files#diff-2f99d92a23bae60fccaee9fcfeda8b77ca73723657662cfadfa4d82751045e14R864) introduced in emberjs/ember.js#19390. Ember.js team is working on a fix; I do not think it is a blocking issue.

**Pull request merged**
